project_id = "qgjfrqdfepxxsxrgkgio"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
external_url = "http://127.0.0.1:54321"
jwt_expiry = 3600
jwt_secret = "super-secret-jwt-token-with-at-least-32-characters-long"
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[functions.generate-ai-content]
verify_jwt = false

[functions.generate-educational-image]
verify_jwt = false