// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgjfrqdfepxxsxrgkgio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnamZycWRmZXB4eHN4cmdrZ2lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMjEwMzUsImV4cCI6MjA2NzY5NzAzNX0.bWFZgyFzHfAt2jLJYII14agTxV1WEABLnS4gIDjLicw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});